springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
        step: 1m
