apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: auth-gateway
spec:
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "beta-auth.flyingjack.top"
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: auth-service
spec:
  hosts:
    - "beta-auth.flyingjack.top"
